### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Potothingi** [SparklyPower/SparklyPaper#14]
What performance benefits does Parallel World Ticking provide?
Do Pathfinder, Entity Tracker, etc. work asynchronously between worlds?

**Comment by MrPowerGamerBR** [comment]
> Do Pathfinder, Entity Tracker, etc. work asynchronously between worlds?

Not asynchronously, they work in parallel

The https://github.com/SparklyPower/SparklyPaper/blob/ver/1.20.4/docs/PARALLEL_WORLD_TICKING.md document explains more about what are the benefits but tl;dr: It is good if you can spread your players in multiple worlds because you can "balance" the load of the worlds into multiple worlds, and the work that you need to do to make plugins work in this environment is way lower compared to Folia. (not bashing Folia here, there are real reasons why plugins need to change a bunch of stuff to make them work in Folia!)
