### ISSUE TITLE
Server specs and config recommendation

### ISSUE THREAD

**Issue by DaddyRobLIVE** [SparklyPower/SparklyPaper#17]
How many minimum CPU threads would you recommend I should have to maximize the benefits of parallel worlds?
>>

parallel-world-ticking:
  threads: 2

Will this work or it really has to be at 8 threads?

**Comment by MrPowerGamerBR** [comment]
You don't need to keep it at 8 threads, you can use whatever thread number you prefer.

Of course, it is better to keep it LESS than the amount of threads your CPU supports (and a bit less than that too, because Minecraft also has other threads for chat, network, etc), but MORE than 1 (if you keep it at 1, then there's no advantage of using parallel world ticking)

**Comment by DaddyRobLIVE** [comment]
I see, it looks like the soft spot for me so far is 3 threads / 5 threads
