### ISSUE TITLE
1.20.6 upstreams?

### ISSUE THREAD

**Issue by DaddyRobLIVE** [SparklyPower/SparklyPaper#18]
Hi, I'm just wondering if the 1.20.6 branch will still get updates or you're focused on 1.21 development now?

**Comment by MrPowerGamerBR** [comment]
I'm focused on 1.21 development because I updated my public server to 1.21, but don't worry, the latest SparklyPaper 1.20.6 version is stable enough for production (I was using it in my public server and I couldn't find any issues with it)

However I **do not** recommend using SparklyPaper 1.21 yet, because Paper 1.21 itself is still missing some very important optimization patches for big servers. With SparklyPaper 1.20.6 I was getting ~100 players with 20 TPS, while with SparklyPaper 1.21 I'm getting ~70 players before TPS starts dropping hard, and most of the TPS issues are due to some of the patches that the Paper team has not updated to 1.21 yet (no I don't blame Paper's team for not updating these patches to 1.21 yet, because if you look at some of the unapplied patches they are HUGE and it makes sense about why Paper hasn't updated these to 1.21 yet), which is why I started taking a crack at updating some of the unapplied patches to 1.21, because they actually fix some big pain points on my server.

I will only recommend updating to SparklyPaper 1.21 after Paper releases stable Paper 1.21 builds (which mean that they have already applied all patches that they deem important)

And because some plugins, while they do say "omg we updated to 1.21!" they are actually not 100% tested on 1.21 and throws exceptions due to ItemStack changes in 1.21.

For future Minecraft updates I will only start updating + shifting dev to the newest Paper version after the Paper team releases stable builds, because at the end of the day I make and maintain SparklyPaper for my own server (SparklyPower).

**Comment by MrPowerGamerBR** [comment]
(Later I really need to release the JAR versions that I do know that worked fine on my server on GitHub's release tab)

**Comment by DaddyRobLIVE** [comment]
Thank you, I just asked since paper still updates papermc version 1.20.6

I also do want to thank you for making this project available to public. This has drastically helped my server handle 100+ players with 20TPS!

I'm hoping to stay with this fork as much as possible and probably send you something in the future if the server earns more donations.

**Comment by MrPowerGamerBR** [comment]
Just a fyi: I'm toying around with the idea of rolling back my server to 1.20.6 (with no backups woo we live on the edge and attempt world downgrades even tho that's a big bad idea but I don't have backups but I'm stupid) because 1.21 is very very very unstable rn so I think I'll wait the Paper team to cook 1.21 a little bit more and then move back to 1.21

I'm still thinking about it tho, if I actually go on with it, then I will make 1.20.6 the "default" SparklyPaper version for now.

![1013117678287855647](https://github.com/SparklyPower/SparklyPaper/assets/9496359/77f9dfa0-ea97-4ced-9fdb-5533490ae964)

**Comment by DaddyRobLIVE** [comment]
Haha. Yeah. Wait for the stable 1.21 by paper before going there.

**Comment by MrPowerGamerBR** [comment]
> Haha. Yeah. Wait for the stable 1.21 by paper before going there.

I've updated SparklyPaper to the latest Paper 1.20.6 commit, and downgraded my server to 1.20.6 for now :3
