### ISSUE TITLE
Update to 1.21?

### ISSUE THREAD

**Issue by DaddyRobLIVE** [SparklyPower/SparklyPaper#27]
https://papermc.io/downloads/paper

Paper has recently released a stable 1.21 version.

**Comment by DaddyRobLIVE** [comment]
I'm guessing you're busy. Hope you're doing well.

**Comment by MrPowerGamerBR** [comment]
> I'm guessing you're busy.

Yeah, as a "one man army", taking care of a Minecraft Server (SparklyPower) and a Discord bot (Loritta) means that it is a bit tricky trying to dedicate time to both projects. Lately I've been working on my Discord bot.

Because SparklyPaper is made for my own server, I end up updating SparklyPaper when I'm ready to update SparklyPower, and because I can already get 90% of Minecraft 1.21 features by enabling the "Minecraft 1.21" Experiment in Minecraft 1.20.6, I'm not in a rush to update to 1.21.

But rest assured SparklyPaper will get an 1.21 update later! As long as SparklyPower is alive and kicking, SparklyPaper will still receive updates, because SparklyPower depends on SparklyPaper. 😛

**Comment by DaddyRobLIVE** [comment]
I understand. Just your reply is more than enough to not lose hope on this project. Take your time and I'm looking forward to the update!

**Comment by DaddyRobLIVE** [comment]
> > I'm guessing you're busy.
> 
> Yeah, as a "one man army", taking care of a Minecraft Server (SparklyPower) and a Discord bot (Loritta) means that it is a bit tricky trying to dedicate time to both projects. Lately I've been working on my Discord bot.
> 
> Because SparklyPaper is made for my own server, I end up updating SparklyPaper when I'm ready to update SparklyPower, and because I can already get 90% of Minecraft 1.21 features by enabling the "Minecraft 1.21" Experiment in Minecraft 1.20.6, I'm not in a rush to update to 1.21.
> 
> But rest assured SparklyPaper will get an 1.21 update later! As long as SparklyPower is alive and kicking, SparklyPaper will still receive updates, because SparklyPower depends on SparklyPaper. 😛

Hi, I hope you're doing well. You're probably very busy but I hope you will find time to update this fork to 1.21.
I really admire your work here and I hope this fork will keep being polished to perfection.

I know you made this solely for your server but you ain't selfish because you made this public and open source. Looking forward for both of our server to fully update to 1.21

**Comment by MrPowerGamerBR** [comment]
1.21.1 builds are now available @ https://github.com/SparklyPower/SparklyPaper/tree/ver/1.21.1 :tada:

These builds weren't tested in production yet, so make backups! What I have tested is that they compile, build, and I was able to login into the server without any issues.

**Comment by DaddyRobLIVE** [comment]
Sure, I'll test it out and report some issues

**Comment by MrPowerGamerBR** [comment]
I have been running the 1.21.1 build for ~14 hours in production and I haven't found any issues :3

**Comment by DaddyRobLIVE** [comment]
That's good to hear! Thanks for the solid work!

**Comment by DaddyRobLIVE** [comment]
By the way, can entities travel through nether portals on this latest update? If not, do you have any plans on fixing this broken mechanic?
