### ISSUE TITLE
log of respawning player

### ISSUE THREAD

**Issue by rudde0** [SparklyPower/SparklyPaper#6]
`[STDOUT] [net.minecraft.server.players.PlayerList] respawning player - current player container is net.minecraft.world.inventory.ContainerPlayer@42958eff but their inventory is net.minecraft.world.inventory.ContainerPlayer@42958eff`

Is it normal? Because it's referencing same inventory but it says "but" in log. Like it was expected something else.

**Comment by MrPowerGamerBR** [comment]
It is normal, once again it is just debug logs I was using to figure out concurrency bugs, but I haven't removed them because it could be useful to track down other bugs

Player Container = the current player's open container (a chest, furnace, etc)
Player Inventory = the instance of the player's inventory (the menu that shows up when you open your own inventory)

**Comment by rudde0** [comment]
ok, thanks for the information
