### ISSUE TITLE
feature request: giant ai

### ISSUE THREAD

**Issue by rudde0** [SparklyPower/SparklyPaper#7]
Hey there,

I know this fork aims to improve performance on high playercounts. Also that's why this is very important for us. There might be some server owners who use Purpur and consider to switch their server software with SparklyPaper.

I just wanted to ask, could you add Giant's AI to server internal, like Purpur did? Mojang removed Giant's AI in 1.8 and it didn't add back. I really need this feature. Also I opened this issue on [Paper's issue page](https://github.com/PaperMC/Paper/issues/9997) but it would be nice if SparklyPaper add this feature to itself.

Thanks for this good fork.

**Comment by MrPowerGamerBR** [comment]
For now this is not planned because, as mentioned in the README, this fork are changes that we need for SparklyPower. And because we don't need this... well, you get the idea.

But for now I will keep the issue open, maybe later I will try adding it, however if I add it and it gets cumbersome to maintain for future versions (but tbh it shouldn't be hard to maintain it), I will scrap it.

And I also think that this isn't impossible to do with plugins tho: You can add your own AI to mobs with Paper's mob goal API, so unless you need Giants to behave exactly like Zombies, you can make your own AI for giants.

**Comment by MrPowerGamerBR** [comment]
Now that the next Minecraft version will allow you to change mob sizes (see https://feedback.minecraft.net/hc/en-us/articles/22483937701517-Minecraft-Java-Edition-Snapshot-23w51b) I think this will be useless, because you will be able to create a zombie that has the same size as a giant, this way you can even mimick giants even in Vanilla Minecraft.

But until then, there's still the "create your own AI goals" solution that you can do with Paper's goal API.

**Comment by rudde0** [comment]
I hope they don't remove this feature until the release, this is such a good feature. ^^
